[phases.setup]
nixPkgs = [
    "python3",
    "pango",
    "gobject-introspection",
    "cairo",
    "gdk-pixbuf",
    "libffi"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "python main.py"
